# Default values for lkloiani-chart.
# This is a YAML-formatted file.
# Declare variables to be passed into your templates.

namespace: "lkloiani"

labels:
  - student: lkloiani

replicaCount: 1

configMap:
  name: index-html-configmap
  data:
    index.html: |
      <html>
      <h1>Welcome</h1>
      </br>
      <h1>Hi! This is a configmap Index file </h1>
      </html>


deployment:
  name: web-server-lkloiani

image:
  name: nginx
  repository: nginx
  pullPolicy: IfNotPresent
  # Overrides the image tag whose default is the chart appVersion.
  tag: ""
  version: "latest"

containerPort: 80

imagePullSecrets: []
nameOverride: ""
fullnameOverride: ""

serviceAccount:
  enabled: true
  name: lkloiani-serviceaccount  

role:
  name:  lkloiani-service-role
  rules:
  - apiGroups: [""] 
    resources: ["pods"]
    verbs: ["get", "list", "watch"]
  - apiGroups: [""] 
    resources: ["configmaps"]
    verbs: ["get","list","watch","create", "delete","update","patch"] 

roleBinding:
  name: "lkloiani-service-role-binding"    

podAnnotations: {}
podLabels: {}

podSecurityContext: {}
  # fsGroup: 2000

securityContext: {}
  # capabilities:
  #   drop:
  #   - ALL
  # readOnlyRootFilesystem: true
  # runAsNonRoot: true
  # runAsUser: 1000

service:
  name: lkloiani-service
  type: ClusterIP
  port: 80

virtualService:
  name: lkloiani-virtual-service
  gateways: 
  - istio-system/academy-ingress-gateway
  hosts:
  - lkloiani.academy.com  

ingress:
  enabled: false
  className: ""
  annotations: {}
    # kubernetes.io/ingress.class: nginx
    # kubernetes.io/tls-acme: "true"
  hosts:
    - host: chart-example.local
      paths:
        - path: /
          pathType: ImplementationSpecific
  tls: []
  #  - secretName: chart-example-tls
  #    hosts:
  #      - chart-example.local

resources: {}
  # We usually recommend not to specify default resources and to leave this as a conscious
  # choice for the user. This also increases chances charts run on environments with little
  # resources, such as Minikube. If you do want to specify resources, uncomment the following
  # lines, adjust them as necessary, and remove the curly braces after 'resources:'.
  # limits:
  #   cpu: 100m
  #   memory: 128Mi
  # requests:
  #   cpu: 100m
  #   memory: 128Mi

livenessProbe:
  httpGet:
    path: /
    port: http
readinessProbe:
  httpGet:
    path: /
    port: http

autoscaling:
  enabled: false
  minReplicas: 1
  maxReplicas: 100
  targetCPUUtilizationPercentage: 80
  # targetMemoryUtilizationPercentage: 80

# Additional volumes on the output Deployment definition.
volumes:
- name: nginx-index-file
  configMap: *configMap.name

# Additional volumeMounts on the output Deployment definition.
volumeMounts:
- name: nginx-index-file
  mountPath: "/usr/share/nginx/html/"
  readOnly: false

nodeSelector: {}

tolerations: []

affinity: {}