apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ .Values.deployment.name }}
  namespace: {{ .Values.namespace }}
  labels:
    {{- range $k, $v := .Values.labels}}
    {{ $k }} : {{ $v }}
    {{- end }}
spec:
  replicas: {{ .Values.replicaCount }}
  selector:
    matchLabels:
      {{- range $k, $v := .Values.labels}}
      {{ $k }} : {{ $v }}
      {{- end }}
  template:
    metadata:
      labels:
        {{- range $k, $v := .Values.labels}}
        {{ $k }} : {{ $v }}
        {{- end }}
    spec:
      containers:
      - name: {{ .Values.image.name }}
        image: {{ .Values.image.repository }}:{{ .Values.image.version }}
        ports:
        - containerPort: {{ .Values.containerPort }}
        volumeMounts:
          - name: {{ .Values.volumeMount.name }}
            mountPath: {{ .Values.volumeMount.mountPath }}
      volumes:
        - name: {{ .Values.volume.name }}
          configMap:
            name: {{ .Values.configMap.name }}   
      serviceAccountName: {{ .Values.serviceAccount.name }}